from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, EmailStr
from sqlalchemy.orm import Session
from app.database import get_db
from app.services.report_generator import generate_pdf_report
from fastapi_mail import FastMail, MessageSchema, ConnectionConfig, MessageType
from typing import List, Optional
import os
import traceback
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

router = APIRouter(prefix="/report")

class EmailRequest(BaseModel):
    email: str # Using str to allow flexibility, but we validate in UI
    tables: List[str]

# SMTP Configuration - Users should set these in .env
port = int(os.getenv("MAIL_PORT", 587))
conf = ConnectionConfig(
    MAIL_USERNAME = os.getenv("MAIL_USERNAME", ""),
    MAIL_PASSWORD = os.getenv("MAIL_PASSWORD", ""),
    MAIL_FROM = os.getenv("MAIL_FROM", os.getenv("MAIL_USERNAME", "noreply@clinicalquality.ai")),
    MAIL_PORT = port,
    MAIL_SERVER = os.getenv("MAIL_SERVER", "smtp.mail.yahoo.com"),
    MAIL_STARTTLS = (port == 587),
    MAIL_SSL_TLS = (port == 465),
    USE_CREDENTIALS = True,
    VALIDATE_CERTS = True
)

@router.post("/send-email")
async def send_email_report(request: EmailRequest, db: Session = Depends(get_db)):
    if not request.tables:
        raise HTTPException(status_code=400, detail="No datasets provided for report")
        
    # Check if SMTP is configured
    if not os.getenv("MAIL_USERNAME") or not os.getenv("MAIL_PASSWORD"):
          # For development, just return a success message if no creds but simulate the PDF generation
          try:
              pdf_path = generate_pdf_report(request.tables, db)
              # In a real app we'd send it, here we just confirm generation
              return {"message": "Report generated. Set MAIL_USERNAME/PASSWORD in .env to enable email sending.", "dev_mode": True}
          except Exception as e:
              raise HTTPException(status_code=500, detail=f"Failed to generate PDF: {str(e)}")

    # 1. Generate PDF
    try:
        pdf_path = generate_pdf_report(request.tables, db)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate PDF: {str(e)}")
        
    # 2. Send Email
    message = MessageSchema(
        subject="Clinical Data Quality Audit Report",
        recipients=[e.strip() for e in request.email.split(',')],
        body="Dear Clinician,\n\nPlease find attached the comprehensive Clinical Data Quality Audit Report generated by our AI validation system.\n\nBest regards,\nClinical Data Quality Team",
        subtype=MessageType.plain,
        attachments=[pdf_path]
    )

    fm = FastMail(conf)
    try:
        await fm.send_message(message)
        # 3. Cleanup PDF
        if os.path.exists(pdf_path):
            os.remove(pdf_path)
        return {"message": "Email sent successfully!"}
    except Exception as e:
        print("Detailed Error Traceback:")
        traceback.print_exc()
        if os.path.exists(pdf_path):
            os.remove(pdf_path)
        raise HTTPException(status_code=500, detail=f"Failed to send email: {str(e)}")

from fastapi.responses import FileResponse
from fastapi import Query

@router.get("/download")
def download_report(tables: List[str] = Query(...), db: Session = Depends(get_db)):
    if not tables:
        raise HTTPException(status_code=400, detail="No datasets provided")
    
    try:
        pdf_path = generate_pdf_report(tables, db)
        return FileResponse(
            pdf_path, 
            media_type='application/pdf', 
            filename=f"Clinical_Audit_Report_{datetime.now().strftime('%Y%m%d')}.pdf"
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate report: {str(e)}")
